version: "3"

services: 
  old-slovaks-express:
    build: .
    ports: 
      - "3000:3000"
    networks: 
      - old-slovaks
  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks: 
      - old-slovaks

networks: 
  old-slovaks: